/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import database.Connector;
import model.KTP;
import controller.Controller;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Raditha & Yohanes Ageng
 */
public class ViewKTP extends javax.swing.JFrame {
    static Connector DB;
    private final Controller ktp;
    /** Creates new form ViewKTP */
    public ViewKTP(Connector DB) {
        initComponents();
        this.DB = DB;
        this.ktp = new Controller(new KTP(DB));
        DefaultTableModel model = (DefaultTableModel)this.tb_data.getModel();
        Object[] row = new Object[13];
        model.setRowCount(0);
        for (int i = 0; ktp.index()[i][0] != null; i++) {
            row[0] = ktp.index()[i][0];
            row[1] = ktp.index()[i][1];
            row[2] = ktp.index()[i][2];
            row[3] = ktp.index()[i][3];
            row[4] = ktp.index()[i][4];
            row[5] = ktp.index()[i][5];
            row[6] = ktp.index()[i][6];
            row[7] = ktp.index()[i][7];
            row[8] = ktp.index()[i][8];
            row[9] = ktp.index()[i][9];
            row[10] = ktp.index()[i][10];
            row[11] = ktp.index()[i][11];
            row[12] = ktp.index()[i][12];
            model.addRow(row);
        }
    }
    
    
    public void search(String str){
      DefaultTableModel tabel = (DefaultTableModel)tb_data.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (tabel);
      tb_data.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_jk = new javax.swing.ButtonGroup();
        txt_status = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_nik = new javax.swing.JTextField();
        txt_ttl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        txt_rt = new javax.swing.JTextField();
        txt_kecamatan = new javax.swing.JTextField();
        txt_rw = new javax.swing.JTextField();
        cb_agama = new javax.swing.JComboBox<>();
        rb_belumkawin = new javax.swing.JRadioButton();
        rb_kawin = new javax.swing.JRadioButton();
        rb_cerai = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rb_perempuan = new javax.swing.JRadioButton();
        rb_laki = new javax.swing.JRadioButton();
        txt_pekerjaan = new javax.swing.JTextField();
        txt_masa = new javax.swing.JTextField();
        txt_negara = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        bt_hapus = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_clear = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txt_caridata = new javax.swing.JTextField();
        bt_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data KTP"));

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Tempat, Tanggal Lahir", "Jenis Kelamin", "Alamat", "RT", "RW", "Kecamatan", "Agama", "Status", "Pekerjaan", "Kewarganegaraan", "Masa Berlaku"
            }
        ));
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_data);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 726, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 285, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Form Data"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tempat, Tanggal Lahir");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("RT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("RW");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Kecamatan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Agama");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Status");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Pekerjaan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Kewarganegaraan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Masa Berlaku");

        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });

        txt_ttl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttlActionPerformed(evt);
            }
        });

        txt_alamat.setColumns(20);
        txt_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        txt_rt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_kecamatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_rw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cb_agama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu", "Penghayat Kepercayaan" }));

        txt_status.add(rb_belumkawin);
        rb_belumkawin.setText("BELUM KAWIN");

        txt_status.add(rb_kawin);
        rb_kawin.setText("KAWIN");
        rb_kawin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_kawinActionPerformed(evt);
            }
        });

        txt_status.add(rb_cerai);
        rb_cerai.setText("CERAI");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Jenis Kelamin");

        txt_jk.add(rb_perempuan);
        rb_perempuan.setText("Perempuan");
        rb_perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_perempuanActionPerformed(evt);
            }
        });

        txt_jk.add(rb_laki);
        rb_laki.setText("Laki - Laki");

        txt_pekerjaan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_masa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_negara.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(159, 159, 159)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txt_ttl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_nik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_nama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_rt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_rw, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(rb_laki)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(rb_perempuan))))
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(cb_agama, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(txt_kecamatan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(rb_belumkawin)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(rb_kawin)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(rb_cerai))
                            .add(txt_pekerjaan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_negara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txt_masa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_nik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txt_nama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txt_ttl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(rb_perempuan)
                    .add(rb_laki))
                .add(11, 11, 11)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txt_rt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txt_rw, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txt_kecamatan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(cb_agama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(rb_belumkawin)
                    .add(rb_kawin)
                    .add(rb_cerai))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_pekerjaan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_negara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(txt_masa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(342, 342, 342))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fitur"));

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_tambah.setText("Tambah");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Cari data");

        txt_caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_caridataKeyReleased(evt);
            }
        });

        bt_keluar.setText("KELUAR");
        bt_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_keluarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel14Layout = new org.jdesktop.layout.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txt_caridata)
                    .add(jPanel14Layout.createSequentialGroup()
                        .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(bt_update, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(bt_tambah, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(bt_clear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(bt_hapus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bt_keluar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel14Layout.createSequentialGroup()
                        .add(bt_tambah)
                        .add(18, 18, 18)
                        .add(bt_update))
                    .add(jPanel14Layout.createSequentialGroup()
                        .add(bt_hapus)
                        .add(18, 18, 18)
                        .add(bt_clear)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel25)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_caridata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bt_keluar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 603, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_ttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttlActionPerformed

    private void rb_kawinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_kawinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_kawinActionPerformed

    private void rb_perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_perempuanActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_nikActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // TODO add your handling code here:
        this.txt_nik.setText("");
        this.txt_nama.setText("");
        this.txt_ttl.setText("");
        this.txt_jk.clearSelection();
        this.txt_alamat.setText("");
        this.txt_kecamatan.setText("");
        this.txt_rt.setText("");
        this.txt_rw.setText("");
        this.cb_agama.setSelectedItem(" ");
        this.txt_status.clearSelection();
        this.txt_pekerjaan.setText("");
        this.txt_negara.setText("");
        this.txt_masa.setText("");
    }//GEN-LAST:event_bt_clearActionPerformed

    private void txt_caridataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_caridataKeyReleased
        // TODO add your handling code here:
        String searcString = txt_caridata.getText();
        search(searcString);
    }//GEN-LAST:event_txt_caridataKeyReleased

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        try{
            String jk = null;
            if (rb_laki.isSelected()) { // Jika memilih laki laki maka akan tercentang laki laki
                jk = "Laki - laki";
            } else if (rb_perempuan.isSelected()) { // Jika memilih laki laki maka akan tercentang Perempuan
                jk = "Perempuan";
            }
            
                String status = null;
                if (rb_belumkawin.isSelected()) { // Jika memilih laki laki maka akan tercentang laki laki
                    status = "BELUM KAWIN";
                } else if (rb_kawin.isSelected()) { // Jika memilih laki laki maka akan tercentang Perempuan
                    status = "KAWIN";
                } else if (rb_cerai.isSelected()){
                    status = "CERAI";
                }
            String nik  = txt_nik.getText();
            String nama = txt_nama.getText();
            String ttl  = txt_ttl.getText();
            String rt   = txt_rt.getText();
            String rw   = txt_rw.getText();
            String alamat = txt_alamat.getText();
            String kecamatan = txt_kecamatan.getText();
            String agama = (String) cb_agama.getSelectedItem();
            String pekerjaan    = txt_pekerjaan.getText();
            String kewarganegaraan  = txt_negara.getText();
            String masaberlaku  = txt_masa.getText();

            ktp.update(nik, nama, ttl, jk, alamat, rt, rw, kecamatan, agama, status, pekerjaan, kewarganegaraan, masaberlaku);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Lengkapi Semua Kolom!");
        }
        DefaultTableModel model = (DefaultTableModel)this.tb_data.getModel();
        Object[] row = new Object[13];
        model.setRowCount(0);
        for (int i = 0; ktp.index()[i][0] != null; i++) {
            row[0] = ktp.index()[i][0];
            row[1] = ktp.index()[i][1];
            row[2] = ktp.index()[i][2];
            row[3] = ktp.index()[i][3];
            row[4] = ktp.index()[i][4];
            row[5] = ktp.index()[i][5];
            row[6] = ktp.index()[i][6];
            row[7] = ktp.index()[i][7];
            row[8] = ktp.index()[i][8];
            row[9] = ktp.index()[i][9];
            row[10] = ktp.index()[i][10];
            row[11] = ktp.index()[i][11];
            row[12] = ktp.index()[i][12];
            model.addRow(row);
        }
    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        try{
            String nik = txt_nik.getText();
            ktp.hapus(nik);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Data Tidak ditemukan!");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tb_data.getModel();
        Object[] row = new Object[13];
        model.setRowCount(0);
        for (int i = 0; ktp.index()[i][0] != null; i++) {
            row[0] = ktp.index()[i][0];
            row[1] = ktp.index()[i][1];
            row[2] = ktp.index()[i][2];
            row[3] = ktp.index()[i][3];
            row[4] = ktp.index()[i][4];
            row[5] = ktp.index()[i][5];
            row[6] = ktp.index()[i][6];
            row[7] = ktp.index()[i][7];
            row[8] = ktp.index()[i][8];
            row[9] = ktp.index()[i][9];
            row[10] = ktp.index()[i][10];
            row[11] = ktp.index()[i][11];
            row[12] = ktp.index()[i][12];
            model.addRow(row);
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        try{
            String jk = null;
            if (rb_laki.isSelected()) { // Jika memilih laki laki maka akan tercentang laki laki
                jk = "Laki - laki";
            } else if (rb_perempuan.isSelected()) { // Jika memilih laki laki maka akan tercentang Perempuan
                jk = "Perempuan";
            }
            
                String status = null;
                if (rb_belumkawin.isSelected()) { 
                    status = "BELUM KAWIN";
                } else if (rb_kawin.isSelected()) { 
                    status = "KAWIN";
                } else if (rb_cerai.isSelected()){
                    status = "CERAI";
                }
            String nik  = txt_nik.getText();
            String nama = txt_nama.getText();
            String ttl  = txt_ttl.getText();
            String rt   = txt_rt.getText();
            String rw   = txt_rw.getText();
            String alamat = txt_alamat.getText();
            String kecamatan = txt_kecamatan.getText();
            String agama = (String) cb_agama.getSelectedItem();
            String pekerjaan    = txt_pekerjaan.getText();
            String kewarganegaraan  = txt_negara.getText();
            String masaberlaku  = txt_masa.getText();
            
            ktp.tambah(nik, nama, ttl, jk, alamat, rt, rw, kecamatan, agama, status, pekerjaan, kewarganegaraan, masaberlaku);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Lengkapi Semua Kolom!");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tb_data.getModel();
        Object[] row = new Object[13];
        model.setRowCount(0);
        for (int i = 0; ktp.index()[i][0] != null; i++) {
            row[0] = ktp.index()[i][0];
            row[1] = ktp.index()[i][1];
            row[2] = ktp.index()[i][2];
            row[3] = ktp.index()[i][3];
            row[4] = ktp.index()[i][4];
            row[5] = ktp.index()[i][5];
            row[6] = ktp.index()[i][6];
            row[7] = ktp.index()[i][7];
            row[8] = ktp.index()[i][8];
            row[9] = ktp.index()[i][9];
            row[10] = ktp.index()[i][10];
            row[11] = ktp.index()[i][11];
            row[12] = ktp.index()[i][12];
            model.addRow(row);
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame ("EXIT"); // Keluar dari program
        if (JOptionPane.showConfirmDialog(frame, "Keluar dari program?", "EXIT",
                JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_bt_keluarActionPerformed

    private void tb_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMouseClicked
        // TODO add your handling code here:
        int baris = tb_data.rowAtPoint(evt.getPoint());    
        String nik = tb_data.getValueAt(baris, 0).toString();
        txt_nik.setText(nik);
        String nama =tb_data.getValueAt(baris, 1).toString();
        txt_nama.setText(nama);
        String ttl =tb_data.getValueAt(baris, 2).toString();
        txt_ttl.setText(ttl);
        if("Perempuan".equals(tb_data.getValueAt(baris, 3).toString())){
            rb_perempuan.setSelected(true);
            }  else {
                    rb_laki.setSelected(true);
                    }
        String alamat =tb_data.getValueAt(baris, 4).toString();
        txt_alamat.setText(alamat);
        String rt = tb_data.getValueAt(baris, 5).toString();
        txt_rt.setText(rt);
        String rw = tb_data.getValueAt(baris, 6).toString();
        txt_rw.setText(rw);
        String kecamatan = tb_data.getValueAt(baris, 7).toString();
        txt_kecamatan.setText(kecamatan);
        String combo = tb_data.getValueAt(baris, 8).toString();
        cb_agama.setSelectedItem(combo);
        if("CERAI".equals(tb_data.getValueAt(baris, 9).toString())){
            rb_cerai.setSelected(true);
            }  else if ("KAWIN".equals(tb_data.getValueAt(baris, 9).toString())) {
                    rb_kawin.setSelected(true);
                    } else {
                            rb_belumkawin.setSelected(true);
                            }
        String pekerjaan = tb_data.getValueAt(baris, 10).toString();
        txt_pekerjaan.setText(pekerjaan);
        String kewarganegaraan = tb_data.getValueAt(baris, 11).toString();
        txt_negara.setText(kewarganegaraan);
        String masaberlaku = tb_data.getValueAt(baris, 12).toString();
        txt_masa.setText(masaberlaku);
    }//GEN-LAST:event_tb_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewKTP(ViewKTP.DB).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_update;
    private javax.swing.JComboBox<String> cb_agama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb_belumkawin;
    private javax.swing.JRadioButton rb_cerai;
    private javax.swing.JRadioButton rb_kawin;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTable tb_data;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_caridata;
    private javax.swing.ButtonGroup txt_jk;
    private javax.swing.JTextField txt_kecamatan;
    private javax.swing.JTextField txt_masa;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_negara;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_pekerjaan;
    private javax.swing.JTextField txt_rt;
    private javax.swing.JTextField txt_rw;
    private javax.swing.ButtonGroup txt_status;
    private javax.swing.JTextField txt_ttl;
    // End of variables declaration//GEN-END:variables

}
